/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailsRouteImport } from './routes/emails'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as RunResearchRouteImport } from './routes/run-research'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsRoute = EmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const RunResearchRoute = RunResearchRouteImport.update({
  id: '/run-research',
  path: '/run-research',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/emails': typeof EmailsRoute
  '/research': typeof ResearchRoute
  '/run-research': typeof RunResearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/emails': typeof EmailsRoute
  '/research': typeof ResearchRoute
  '/run-research': typeof RunResearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/emails': typeof EmailsRoute
  '/research': typeof ResearchRoute
  '/run-research': typeof RunResearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/emails' | '/research' | '/run-research'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/emails' | '/research' | '/run-research'
  id: '__root__' | '/' | '/emails' | '/research' | '/run-research'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmailsRoute: typeof EmailsRoute
  ResearchRoute: typeof ResearchRoute
  RunResearchRoute: typeof RunResearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails': {
      id: '/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof EmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run-research': {
      id: '/run-research'
      path: '/run-research'
      fullPath: '/run-research'
      preLoaderRoute: typeof RunResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmailsRoute: EmailsRoute,
  ResearchRoute: ResearchRoute,
  RunResearchRoute: RunResearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
